mod 'puppet-nginx', '2.1.1'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'puppetlabs/apt'
mod 'puppetlabs/powershell'
mod 'puppetlabs/reboot'
mod 'puppetlabs/docker'
mod 'samuelson-dockeragent'
